### PR TITLE
Support multiple Yubikeys and load all slots

### LINKED ISSUE #22: Generate two keys with different touch policies
It should be possible to support two different keys with different touch policy on Yubikey. This would allow having some more sensitive services require a touch, but also enable other services to still use the hardware key but no touch required, only PIN per session.

Primary use case for me now is Github; I have auto-fetch on my editor and it keeps prompting for touch. It is making way too many (unidentified, #8 ) prompts for touch. If I could use a second slot on the same key for no-touch use cases, it would not be a problem, as long as SSH doesn't trigger signing and therefore touch for the passive other key with touch-required.

### PR DESCRIPTION
**Pull request by joneskoo**
Fixes #22

### CODE REVIEW

**Comment by joneskoo** [comment]
Based on comment in main ticket I suspect my PR doesn’t handle if key can’t be read. Weird because I only have two certificates and it works for me. Will need to look at this if I can find a problem. Perhaps it’s ok if slot 9a has a valid certificate and others get ignored.

**Comment by joneskoo** [comment]
Just to update this PR status. I'm hoping to get feedback whether it's welcome to support multiple slots per key. This PR supports both multiple slots and multiple keys - which arguably could be split to separate PRs.

Personally I only care about the multiple slots - I'm happy to rebase and improve based on review comments. I won't rebase only for the multiple Yubikeys. I can rebase the multiple slots after receiving some feedback what are the conditions to get that merged, and if possible, I'd welcome some help getting consistent benchmarks so we know if adding multiple slot support degrades performance for most users or not.

I don't mind at all if someone picks the multiple yubikeys part of this PR and makes a cleaned up and new PR on it. I will not.

**Comment by smlx** [comment]
My 2c: multiple slots has the most straightforward use-case (as per #22), and I don't understand the use-case for multiple keys.

**Comment by joneskoo** [comment]
Let me rebase and start again, including only "load all slots".

**Comment by nrpeterson** [comment]
@joneskoo @smlx For what it is worth, I actually think support for multiple YubiKeys would be *stellar*.

One use case: I keep a YubiKey 5c nano in my macbook; it is convenient and easy. But, I maintain slightly higher security by keeping a separate YubiKey 5c NFC for more sensitive credentials / services / systems.

You could also easily picture not wanting to intermingle identities / credentials related to personal projects and work projects, but occasionally wanting to log in to a personal system from work.

**Pull request closed without merging**
