### PR TITLE
Ignore cards which aren't YubiKeys

### PR DESCRIPTION
**Pull request by smlx**
I've got another smart card reader built into my laptop that `yubikey-agent` tries to use and fails.

This fixes the issue.

### CODE REVIEW

**Comment by joneskoo** [comment]
Wonder if #27 works for you? I don't even have multiple Yubikeys to test. But perhaps it's better to implement support multiple Yubikeys instead of allow listing specifically Yubikeys?

Feel free to extract my multiple Yubikey implementation as I'm not getting feedback whether my PR loading multiple slots is welcome.

**Comment by smlx** [comment]
The specific problem this PR fixes for me is in setup which I don't think #27 addresses. There could be some overlap between the two for agent functionality though.

**Comment by FiloSottile** [comment]
Although called yubikey-agent, the tool works well with Solo Keys as well as probably any other PIV token. I wouldn't want to lose that. I realize it's a fairly unsatisfying answer, but since `-setup` is called once in a key lifetime, and so few people have multiple PIV tokens, I think unplugging all other ones when calling `-setup` is a reasonable answer.

**Comment by smlx** [comment]
> I think unplugging all other ones when calling -setup is a reasonable answer.

From the description:

> I've got another smart card reader __built into__ my laptop that yubikey-agent tries to use and fails.

So unplugging is not possible.

> so few people have multiple PIV tokens

Really? I was under the impression that it is best practice to have at least one backup yubikey so that when the main one fails you aren't locked out of all accounts.

That said, maybe I'm unusual. I'm already carrying this patch locally so I'm happy to just continue that.

**Pull request closed without merging**
