### PR TITLE
Switch to github.com/twpayne/go-pinentry-minimal

### PR DESCRIPTION
**Pull request by twpayne**
As [suggested by the author of github.com/gopasspw/pinentry](https://github.com/FiloSottile/age/pull/386#issuecomment-1008714823).

### CODE REVIEW

**Comment by FiloSottile** [comment]
The extra dependencies are a blocker, better pinentry support is not worth pulling in dependencies from three different organizations/authors. Are they necessary non-test dependencies of go-pinentry?

**Comment by twpayne** [comment]
> Are they necessary non-test dependencies of go-pinentry?

Nope, they're there for rich functionality, not necessary functionality. The core pinentry functionality only depends on the Go standard library.

Would you accept a version of go-pinentry that only has standard library dependencies?

**Comment by FiloSottile** [comment]
Yeah, it looks comparable in amount of complexity, if the gopasspw folks recommended it I'd be happy to switch.

**Comment by twpayne** [comment]
OK, PR updated to use the minimal fork: https://github.com/twpayne/go-pinentry-minimal.

PTA(nother)L.

**Comment by FiloSottile** [comment]
LGTM, thank you. Please drop the .gitignore commit, I generally prefer not to check in workflow-specific gitignores.

**Comment by twpayne** [comment]
> Please drop the .gitignore commit

Done.

**Pull request merged**
