### PR TITLE
yubikey-agent: add systemd/Linux setup instructions

### PR DESCRIPTION
**Pull request by mdlayher**
Works on my machine(tm)!

### CODE REVIEW

**Comment by LeSuisse** [comment]
The proposed setup is likely to not work in most cases:
 * the socket will not be writable because by default the umask will be set to 0022
 * the PC/SC daemon might not be started
 * pinentry is likely to be lost when started from a system service because it will not know how to ask the user for the PIN

I ended up creating a systemd user service (`~/.config/systemd/user/yubikey-agent.service`) with the following content (most of it is here to make `systemd-analyze security` happy):

```
[Unit]
Description=Seamless ssh-agent for YubiKeys
Documentation=https://filippo.io/yubikey-agent

[Service]
ExecStart=/usr/local/bin/yubikey-agent -l %t/yubikey-agent/yubikey-agent.sock
ExecReload=/bin/kill -HUP $MAINPID
ProtectSystem=strict
ProtectKernelLogs=yes
ProtectKernelModules=yes
ProtectKernelTunables=yes
ProtectControlGroups=yes
ProtectClock=yes
ProtectHostname=yes
PrivateTmp=yes
PrivateDevices=yes
PrivateUsers=yes
IPAddressDeny=any
RestrictAddressFamilies=AF_UNIX
RestrictNamespaces=yes
RestrictRealtime=yes
RestrictSUIDSGID=yes
LockPersonality=yes
CapabilityBoundingSet=
SystemCallFilter=@system-service
SystemCallFilter=~@privileged @resources
SystemCallErrorNumber=EPERM
SystemCallArchitectures=native
NoNewPrivileges=yes
KeyringMode=private
UMask=0177
RuntimeDirectory=yubikey-agent

[Install]
WantedBy=multi-user.target
```

Then refresh systemd daemon configuration, make sure that PC/SC daemon will be available and start the yubikey-agent:
```
$ systemctl daemon-reload --user
$ sudo systemctl start pcscd.socket
$ systemctl --user start yubikey-agent
```

**Comment by mdlayher** [comment]
I'll take your word for it. Want to open a PR to replace this one? I'm no systemd unit expert.

**Comment by LeSuisse** [comment]
Sure, done in #20 ;) .

**Comment by mdlayher** [comment]
Thank you!

**Pull request closed without merging**
